codecov:
  notify:
    require_ci_to_pass: yes
  strict_yaml_branch: main  # only use the latest copy on the main branch

ignore:
  - "**/*.pb.go"
  - "proto-gen/*/*"
  - "thrift-gen/*/*"

coverage:
  precision: 2
  round: down
  range: "85...100"
  status:
    project:
      default:
        enabled: yes
        target: 85%
    patch:
      default:
        enabled: yes
        target: 90%
