codecov:
  notify:
    require_ci_to_pass: yes
  strict_yaml_branch: main  # only use the latest copy on the main branch

ignore:
  - "model/v1/model.pb.go"
  - "proto-gen/*/*"

coverage:
  precision: 2
  round: down
  range: "95...100"
  status:
    project:
      default:
        enabled: yes
        target: 95%
    patch:
      default:
        enabled: yes
        target: 95%