# Copyright (c) 2023 The Jaeger Authors.
# SPDX-License-Identifier: Apache-2.0

# Codecov upload often fails on rate limits if used without a token.
# See https://github.com/codecov/codecov-action/issues/837
# This action embeds a token directly.
# We cannot define it as "secret" as we need it accessible from forks.

name: 'Upload coverage to codecov'
description: 'Uploads coverage to codecov with retries'
inputs:
  files:
    description: 'Coverage files to upload'
    required: true
  flags:
    description: 'Flags for codecov'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Retry upload
      uses: Wandalen/wretry.action@v3.7.0
      with:
        attempt_limit: 6
        # sleep 10 seconds between retries
        attempt_delay: 10000
        action: codecov/codecov-action@v5
        with: |
          slug: jaegertracing/jaeger-idl
          files: ${{ inputs.files }}
          flags: ${{ inputs.flags }}
          verbose: true
          fail_ci_if_error: true
          token: 95fab3d9-8038-40ba-ac56-0d8bd91390a4