// Code generated by Thrift Compiler (0.19.0). DO NOT EDIT.

// Copyright (c) 2025 The Jaeger Authors.
// SPDX-License-Identifier: Apache-2.0


package agent

import (
	"bytes"
	"context"
	"errors"
	"fmt"
	"time"
	"strings"
	"regexp"

	thrift "github.com/apache/thrift/lib/go/thrift"

	"github.com/jaegertracing/jaeger-idl/thrift-gen/jaeger"
	"github.com/jaegertracing/jaeger-idl/thrift-gen/zipkincore"
)

// (needed to ensure safety because of naive import list construction.)
var _ = thrift.ZERO
var _ = fmt.Printf
var _ = errors.New
var _ = context.Background
var _ = time.Now
var _ = bytes.Equal
// (needed by validator.)
var _ = strings.Contains
var _ = regexp.MatchString

var _ = jaeger.GoUnusedProtection__
var _ = zipkincore.GoUnusedProtection__

func init() {
}

